[tshark]
# Specify the path to the tshark executable.
# If the configured path does not exist, these locations will be searched:
# (Linux): /usr/bin/tshark
# (Linux): /usr/sbin/tshark
# (Linux): /usr/lib/tshark/tshark
# (Linux): /usr/local/bin/tshark
# (Linux): /bin/tshark
# (Windows): %ProgramFiles%\Wireshark\tshark.exe
# (Windows): %ProgramFiles(x86)%\Wireshark\tshark.exe
; tshark_path = C:\Program Files\Wireshark\tshark.exe
; tshark_path = C:\Users\ylx\Desktop\Courses\WiresharkDev\wsbuild64\run\RelWithDebInfo\tshark.exe
; tshark_path = /home/lxyu/wireshark-dev/wsbuild/run/tshark
tshark_path = C:\Users\ylx\Desktop\Courses\WiresharkNewest\wsbuild64\run\RelWithDebInfo\tshark.exe

; [dumpcap]
; dumpcap_path = C:\Program Files\Wireshark\dumpcap.exe

[normal]
enabled = true
tshark_path = tshark

[vmess]
enabled = true
tshark_path = /home/lxyu/wireshark-dev/wsbuild/run/tshark

[shadowsocks]
enabled = true
tshark_path = C:\Users\ylx\Desktop\Courses\WiresharkDev\wsbuild64\run\RelWithDebInfo\tshark.exe

[trojan]
enabled = true
tshark_path = C:\Users\ylx\Desktop\Courses\WiresharkNewest\wsbuild64\run\RelWithDebInfo\tshark.exe

[firefox]
firefox_path = /home/lxyu/firefox_legacy/firefox-140/firefox